### ISSUE TITLE
请求提供 rss 订阅

### ISSUE THREAD

**Issue by lyh543** [chaptsand/chaptsand.github.io#1]
可以支持一下 rss 订阅吗？我看这个 Hexo 主题是[支持 rss 的](https://keep-docs.xpoet.cn/usage-tutorial/configuration-guide.html#rss)。

顺便 https://www.chaptsand.top/ 还没有正确 CNAME 到 github.io 上。

**Comment by chaptsand** [comment]
好久没维护博客了，感谢提醒！
好的前几天域名到期了，我暂时把CNAME给删了哈哈

**Comment by lyh543** [comment]
https://www.chaptsand.top/atom.xml

好耶！
